#!/bin/bash
g++ Card.cpp Firework.cpp Klondike.cpp main.cpp Storage.cpp -o klondike.exe -m32 -std=c++17 -l SDL2main -l SDL2 -l SDL2_image -I "/home/kindfox/Dev/SDL2/include" -L "/home/kindfox/Dev/SDL2/lib/x86" -static-libgcc
#there're some problems
